version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test0310Project
  gitServerName: remoteGit
  gitUrl: https://github.com/Hariharan-SV-IBM
  gitUsername: Hariharan-SV-IBM
  gitBranch: main
- name: TPP01
  gitServerName: remoteGit
  gitUrl: https://github.com/Hariharan-SV-IBM
  gitUsername: Hariharan-SV-IBM
  gitBranch: master
